### ISSUE TITLE
Project Proposal Notes

### ISSUE THREAD

**Issue by wongshington** [gflujan/AudioCaelum#1]
Gabriel Lujan - SoundCloud

  The content looks pretty good, but just add them into their own pages under your wiki so they're all in one place. We can talk more about these design docs later on when we meet too. Everything looks solid so far, I would take another look at your schema and think about how we can keep our schema simple and flexible.

# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
  - [x] Includes the following list for the 4 app specific MVPs:
    - [x] Adequate styling
    - [x] Smooth, bug-free navigation
    - [x] Adequate and appropriate seeds to demonstrate the feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
  + add some more information about each MVP. What will it mean to have one of them complete? This is always good practice to set clear expectations plans for completion. 
  + 
---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
  + for the `follows` and `followers` tables, try and brainstorm what information would need to get stored in those tables and is there a way to use the same table for that stored information. What relationship/information are those tables being used to record?
  + also consider if we need a table for artists specifically and a separate one for the rest of the users. I think for Soundcloud anyone can upload a track and anyone can listen to one

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
  + looks really complete, but should be in markdown formatted to show as a code snippet so it's easier to read

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
  + trust your instincts on this one, you mention maybe not needing a route if you make use of your associations. That's a good call if users would likely not see the comments to a song without also needing to see the song information.
---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments
  + will you need a `/logout` route?
  + will your routes need to be this specific, remember if you're using differently named routes it becomes harder to conditionally render certain components together.

**Comment by gflujan** [comment]
@wongshington 
Alright, I moved each doc file into it's own page on the wiki. I removed unnecessary routes from my backend. 

Regarding the schema, I removed the `artists` table & I'm only going to focus on the first 4 tables (users, songs, comments, follows). The last 4 are just notes for when/if I get to those bonus features somewhere down the line. 

For the "follows/followers" tables, I consolidated them and made them into a joins table. I realized it's just a connection between users to see who's following whom. The one piece I'll ask you to look at is the corresponding associations on the `users` table. 

I added the tick marks to the sample state. I forgot about those. :-) 

The `/logout` route is a part of SoundCloud and it's just a landing page for after the user signs out. They display (basically) an advertisement for their mobile apps. I guess it's not strictly needed as I could just redirect the user to the home page after logout. With that in mind, I've put it into the "bonus" category. 

Finally, I added some bullet points to my MVP's about the completion impact of each feature. 

Please take a look and let me know what you think. Thanks!

**Comment by wongshington** [comment]
Sounds good on the bonus tables in your schema. The associations look solid for your Users model as well. I have a solid idea of where you're going for each MVP as well. Get started on User Auth and we can go from there. Good stuff!
