### ISSUE TITLE
MVP #1 Sign Off - Session Auth

### ISSUE THREAD

**Issue by gflujan** [gflujan/AudioCaelum#3]
Alright, session auth (login, account creation & demo login) are good to go.

**Comment by wongshington** [comment]
- [ ] when trying to sign up, if you get password errors, they don't get rendered
- [ ] it lets me continue past the email input page without putting in an email
- [ ] some strange behavior when i try to log in using a previously created user email
![screen shot 2019-03-05 at 11 23 35 am](https://user-images.githubusercontent.com/26219652/53831280-4f70f780-3f39-11e9-8ca7-24df0ecea0c8.png)

**Comment by gflujan** [comment]
Alright, all 3 should be good to go now.
